[forest]
host = "jonmsterling"
trees = ["trees"]
assets = ["assets"]
theme = "theme"
foreign = ["foreign/forester-notes.org.json", "erct/output/erct.json"]
url = "https://www.jonmsterling.com/"

[renderer]
home = "index"

