[forest]
host = "jonmsterling"
trees = ["trees"]
assets = ["assets"]
theme = "theme"
foreign = ["foreign/forester-notes.org.json", "erct/publications/erct.json"]

[renderer]
home = "jms-0001"
base_url = "http://www.jonmsterling.com/"

