name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.0"

      - name: Install Forester
        run: |
          git clone https://github.com/jonsterling/ocaml-forester.git
          cd ocaml-forester
          opam pin add -y . --locked

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            scheme-medium
            standalone
            mlmodern
            amsfonts
            amsmath
            zx-calculus
            tikz-cd
            l3packages
            dvisvgm
            pgf
            etoolbox
            mathtools
            stmaryrd
            newtx
            newpx
            xstring
            fontaxes
            kastrup

      - name: Check `latex` version
        run: latex --version

      - name: Build with Forester
        run: opam exec -- forester --root jms-0001 trees

      - name: Setup upterm session
        if: failure()
        uses: lhotari/action-upterm@v1


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          cname: www.jonmsterling.com
